-- SIGERD
-- Fase 2 - Nucleo operacional minimo viavel
-- MySQL 8+ / MariaDB compativel

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS usuarios_escopos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    usuario_id BIGINT UNSIGNED NOT NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NULL,
    escopo_acesso ENUM(
        'PROPRIA_UNIDADE',
        'PROPRIO_ORGAO',
        'MUNICIPAL',
        'REGIONAL',
        'ESTADUAL',
        'MULTIINSTITUCIONAL',
        'GLOBAL'
    ) NOT NULL,
    status_escopo ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuarios_escopos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_usuarios_escopos_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_usuarios_escopos_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    UNIQUE KEY uk_usuarios_escopos_usuario_escopo (usuario_id, escopo_acesso),
    KEY idx_usuarios_escopos_contexto (conta_id, orgao_id, status_escopo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS incidentes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    numero_ocorrencia VARCHAR(60) NOT NULL,
    nome_incidente VARCHAR(180) NOT NULL,
    tipo_ocorrencia VARCHAR(100) NOT NULL,
    classificacao_inicial VARCHAR(60) NULL,
    data_hora_acionamento DATETIME NULL,
    data_hora_abertura DATETIME NOT NULL,
    municipio VARCHAR(120) NULL,
    local_detalhado VARCHAR(255) NULL,
    coordenadas VARCHAR(120) NULL,
    orgao_primeira_informacao VARCHAR(180) NULL,
    canal_recebimento VARCHAR(80) NULL,
    comunicante VARCHAR(180) NULL,
    descricao_inicial TEXT NOT NULL,
    situacao_inicial_observada TEXT NULL,
    populacao_potencialmente_afetada INT UNSIGNED NULL,
    danos_humanos_iniciais TEXT NULL,
    danos_materiais_iniciais TEXT NULL,
    danos_ambientais_iniciais TEXT NULL,
    riscos_imediatos TEXT NULL,
    orgao_lider_inicial VARCHAR(180) NULL,
    status_incidente ENUM('ABERTO', 'EM_ANDAMENTO', 'CONTROLADO', 'ENCERRADO') NOT NULL DEFAULT 'ABERTO',
    plancon_id BIGINT UNSIGNED NULL,
    cenario_id BIGINT UNSIGNED NULL,
    aberto_por_usuario_id BIGINT UNSIGNED NOT NULL,
    encerrado_por_usuario_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_incidentes_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_incidentes_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_incidentes_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_incidentes_usuario_abertura FOREIGN KEY (aberto_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_incidentes_usuario_encerramento FOREIGN KEY (encerrado_por_usuario_id) REFERENCES usuarios(id),
    UNIQUE KEY uk_incidentes_orgao_numero (orgao_id, numero_ocorrencia),
    KEY idx_incidentes_escopo_status (conta_id, orgao_id, unidade_id, status_incidente),
    KEY idx_incidentes_data_abertura (data_hora_abertura),
    KEY idx_incidentes_plancon (plancon_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS incidentes_briefing (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    incidente_id BIGINT UNSIGNED NOT NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    versao_briefing INT UNSIGNED NOT NULL DEFAULT 1,
    resumo_situacao TEXT NOT NULL,
    eventos_significativos TEXT NULL,
    objetivos_iniciais TEXT NULL,
    acoes_atuais TEXT NULL,
    recursos_alocados TEXT NULL,
    recursos_solicitados TEXT NULL,
    riscos_criticos_seguranca TEXT NULL,
    restricoes_operacionais TEXT NULL,
    necessidades_imediatas TEXT NULL,
    responsavel_briefing VARCHAR(180) NULL,
    data_hora_briefing DATETIME NULL,
    uso_transferencia_comando TINYINT(1) NOT NULL DEFAULT 0,
    observacoes TEXT NULL,
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_incidentes_briefing_incidente FOREIGN KEY (incidente_id) REFERENCES incidentes(id),
    CONSTRAINT fk_incidentes_briefing_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_incidentes_briefing_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_incidentes_briefing_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_incidentes_briefing_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    UNIQUE KEY uk_incidentes_briefing_versao (incidente_id, versao_briefing),
    KEY idx_incidentes_briefing_escopo (conta_id, orgao_id, incidente_id),
    KEY idx_incidentes_briefing_data (data_hora_briefing)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS incidentes_comando (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    incidente_id BIGINT UNSIGNED NOT NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    tipo_comando ENUM('UNICO', 'UNIFICADO') NOT NULL DEFAULT 'UNICO',
    comandante_usuario_id BIGINT UNSIGNED NULL,
    comandante_nome VARCHAR(180) NULL,
    instituicao_comandante VARCHAR(180) NULL,
    autoridade_legal TEXT NULL,
    comando_unificado TEXT NULL,
    data_hora_assuncao DATETIME NULL,
    data_hora_transferencia DATETIME NULL,
    motivo_transferencia TEXT NULL,
    base_legal_ativacao TEXT NULL,
    local_posto_comando VARCHAR(180) NULL,
    status_comando ENUM('ATIVO', 'TRANSFERIDO', 'ENCERRADO') NOT NULL DEFAULT 'ATIVO',
    diretrizes_institucionais TEXT NULL,
    restricoes_juridicas_operacionais TEXT NULL,
    observacoes TEXT NULL,
    atualizado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_incidentes_comando_incidente FOREIGN KEY (incidente_id) REFERENCES incidentes(id),
    CONSTRAINT fk_incidentes_comando_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_incidentes_comando_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_incidentes_comando_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_incidentes_comando_usuario_cmd FOREIGN KEY (comandante_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_incidentes_comando_usuario_atualizacao FOREIGN KEY (atualizado_por_usuario_id) REFERENCES usuarios(id),
    UNIQUE KEY uk_incidentes_comando_incidente (incidente_id),
    KEY idx_incidentes_comando_escopo (conta_id, orgao_id, status_comando)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS incidentes_periodos_operacionais (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    incidente_id BIGINT UNSIGNED NOT NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    numero_periodo INT UNSIGNED NOT NULL,
    data_hora_inicio DATETIME NOT NULL,
    data_hora_fim DATETIME NULL,
    situacao_inicial_periodo TEXT NULL,
    objetivos_periodo TEXT NULL,
    recursos_principais_periodo TEXT NULL,
    briefing_realizado TINYINT(1) NOT NULL DEFAULT 0,
    pai_vinculado VARCHAR(180) NULL,
    situacao_encerramento TEXT NULL,
    pendencias TEXT NULL,
    responsavel_aprovacao VARCHAR(180) NULL,
    status_periodo ENUM('PLANEJADO', 'ATIVO', 'ENCERRADO') NOT NULL DEFAULT 'ATIVO',
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_incidentes_periodos_incidente FOREIGN KEY (incidente_id) REFERENCES incidentes(id),
    CONSTRAINT fk_incidentes_periodos_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_incidentes_periodos_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_incidentes_periodos_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_incidentes_periodos_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    UNIQUE KEY uk_incidentes_periodos_numero (incidente_id, numero_periodo),
    KEY idx_incidentes_periodos_status (conta_id, orgao_id, status_periodo),
    KEY idx_incidentes_periodos_data (data_hora_inicio, data_hora_fim)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS incidentes_registros_operacionais (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    incidente_id BIGINT UNSIGNED NOT NULL,
    periodo_operacional_id BIGINT UNSIGNED NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    data_hora_registro DATETIME NOT NULL,
    tipo_registro ENUM('DECISAO', 'ACIONAMENTO', 'OCORRENCIA', 'MOBILIZACAO', 'ATUALIZACAO', 'COMUNICADO') NOT NULL,
    titulo_registro VARCHAR(180) NOT NULL,
    descricao_registro TEXT NOT NULL,
    origem_informacao VARCHAR(180) NULL,
    responsavel_lancamento VARCHAR(180) NULL,
    encaminhamento TEXT NULL,
    status_registro ENUM('ABERTO', 'EM_ANDAMENTO', 'CONCLUIDO') NOT NULL DEFAULT 'ABERTO',
    criticidade ENUM('BAIXA', 'MODERADA', 'ALTA', 'CRITICA') NOT NULL DEFAULT 'MODERADA',
    dados_json JSON NULL,
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_incidentes_registros_incidente FOREIGN KEY (incidente_id) REFERENCES incidentes(id),
    CONSTRAINT fk_incidentes_registros_periodo FOREIGN KEY (periodo_operacional_id) REFERENCES incidentes_periodos_operacionais(id),
    CONSTRAINT fk_incidentes_registros_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_incidentes_registros_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_incidentes_registros_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_incidentes_registros_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    KEY idx_incidentes_registros_escopo (conta_id, orgao_id, incidente_id, data_hora_registro),
    KEY idx_incidentes_registros_tipo (tipo_registro, status_registro),
    KEY idx_incidentes_registros_periodo (periodo_operacional_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
