-- SIGERD
-- Fase 3 - Expansao do PLANCON e do gerenciamento de desastres
-- MySQL 8+ / MariaDB compativel

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS plancons (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    titulo_plano VARCHAR(180) NOT NULL,
    municipio_estado VARCHAR(180) NULL,
    versao_documento VARCHAR(40) NULL,
    data_elaboracao DATE NULL,
    data_ultima_atualizacao DATE NULL,
    responsavel_tecnico VARCHAR(180) NULL,
    contato_institucional VARCHAR(180) NULL,
    vigencia_inicio DATE NULL,
    vigencia_fim DATE NULL,
    area_abrangencia TEXT NULL,
    tipo_desastre_principal VARCHAR(120) NULL,
    outros_desastres_associados TEXT NULL,
    base_legal_utilizada TEXT NULL,
    objetivo_geral TEXT NULL,
    objetivos_especificos TEXT NULL,
    publico_alvo TEXT NULL,
    status_plancon ENUM('RASCUNHO', 'ATIVO', 'EM_REVISAO', 'ARQUIVADO', 'VENCIDO') NOT NULL DEFAULT 'RASCUNHO',
    observacoes_gerais TEXT NULL,
    criado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    atualizado_por_usuario_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_plancons_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_plancons_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_plancons_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_plancons_usuario_criador FOREIGN KEY (criado_por_usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_plancons_usuario_atualizador FOREIGN KEY (atualizado_por_usuario_id) REFERENCES usuarios(id),
    UNIQUE KEY uk_plancons_orgao_titulo_versao (orgao_id, titulo_plano, versao_documento),
    KEY idx_plancons_escopo_status (conta_id, orgao_id, unidade_id, status_plancon),
    KEY idx_plancons_vigencia (vigencia_inicio, vigencia_fim)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS plancon_riscos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    plancon_id BIGINT UNSIGNED NOT NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    tipo_ameaca VARCHAR(120) NULL,
    descricao_risco TEXT NOT NULL,
    origem_risco TEXT NULL,
    historico_ocorrencias TEXT NULL,
    frequencia_ocorrencia VARCHAR(60) NULL,
    periodo_sazonal VARCHAR(60) NULL,
    areas_suscetiveis TEXT NULL,
    populacao_exposta VARCHAR(120) NULL,
    infraestruturas_expostas TEXT NULL,
    vulnerabilidades_identificadas TEXT NULL,
    capacidade_local_resposta TEXT NULL,
    probabilidade_evento VARCHAR(40) NULL,
    impacto_potencial VARCHAR(40) NULL,
    nivel_risco ENUM('BAIXO', 'MODERADO', 'ALTO', 'MUITO_ALTO') NULL,
    fatores_agravantes TEXT NULL,
    fatores_atenuantes TEXT NULL,
    fontes_informacao_utilizadas TEXT NULL,
    responsavel_analise VARCHAR(180) NULL,
    data_analise DATE NULL,
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_plancon_riscos_plancon FOREIGN KEY (plancon_id) REFERENCES plancons(id),
    CONSTRAINT fk_plancon_riscos_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_plancon_riscos_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_plancon_riscos_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_plancon_riscos_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    KEY idx_plancon_riscos_escopo (conta_id, orgao_id, plancon_id),
    KEY idx_plancon_riscos_nivel (tipo_ameaca, nivel_risco)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS plancon_cenarios (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    plancon_id BIGINT UNSIGNED NOT NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    nome_cenario VARCHAR(120) NOT NULL,
    tipo_desastre_associado VARCHAR(120) NULL,
    descricao_cenario TEXT NOT NULL,
    evento_disparador VARCHAR(180) NULL,
    area_afetada_estimada TEXT NULL,
    populacao_potencialmente_afetada VARCHAR(120) NULL,
    danos_humanos_esperados TEXT NULL,
    danos_materiais_esperados TEXT NULL,
    danos_ambientais_esperados TEXT NULL,
    danos_sociais_esperados TEXT NULL,
    servicos_interrompidos TEXT NULL,
    tempo_evolucao_evento VARCHAR(80) NULL,
    necessidades_iniciais TEXT NULL,
    prioridades_operacionais TEXT NULL,
    classificacao_cenario ENUM('BAIXA', 'MODERADA', 'ALTA', 'CRITICA') NULL,
    observacoes_cenario TEXT NULL,
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_plancon_cenarios_plancon FOREIGN KEY (plancon_id) REFERENCES plancons(id),
    CONSTRAINT fk_plancon_cenarios_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_plancon_cenarios_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_plancon_cenarios_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_plancon_cenarios_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    UNIQUE KEY uk_plancon_cenarios_nome (plancon_id, nome_cenario),
    KEY idx_plancon_cenarios_escopo (conta_id, orgao_id, plancon_id),
    KEY idx_plancon_cenarios_classificacao (classificacao_cenario)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS plancon_niveis_ativacao (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    plancon_id BIGINT UNSIGNED NOT NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    nivel_operacional VARCHAR(60) NOT NULL,
    criterios_ativacao TEXT NULL,
    gatilhos_acionamento TEXT NULL,
    autoridade_responsavel VARCHAR(180) NULL,
    acoes_automaticas TEXT NULL,
    procedimentos_escalonamento TEXT NULL,
    status_nivel ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO',
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_plancon_ativacao_plancon FOREIGN KEY (plancon_id) REFERENCES plancons(id),
    CONSTRAINT fk_plancon_ativacao_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_plancon_ativacao_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_plancon_ativacao_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_plancon_ativacao_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    UNIQUE KEY uk_plancon_ativacao_nivel (plancon_id, nivel_operacional),
    KEY idx_plancon_ativacao_escopo_status (conta_id, orgao_id, status_nivel)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS plancon_recursos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    plancon_id BIGINT UNSIGNED NOT NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    tipo_recurso VARCHAR(120) NOT NULL,
    categoria_recurso VARCHAR(120) NULL,
    descricao_recurso TEXT NOT NULL,
    quantidade_disponivel DECIMAL(12,2) NULL,
    unidade_medida VARCHAR(30) NULL,
    localizacao_base VARCHAR(180) NULL,
    tempo_mobilizacao VARCHAR(80) NULL,
    status_recurso ENUM('DISPONIVEL', 'INDISPONIVEL', 'EM_MANUTENCAO') NOT NULL DEFAULT 'DISPONIVEL',
    responsavel_recurso VARCHAR(180) NULL,
    contato_responsavel VARCHAR(180) NULL,
    observacoes TEXT NULL,
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_plancon_recursos_plancon FOREIGN KEY (plancon_id) REFERENCES plancons(id),
    CONSTRAINT fk_plancon_recursos_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_plancon_recursos_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_plancon_recursos_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_plancon_recursos_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    KEY idx_plancon_recursos_escopo (conta_id, orgao_id, plancon_id),
    KEY idx_plancon_recursos_status (tipo_recurso, status_recurso)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS plancon_revisoes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    plancon_id BIGINT UNSIGNED NOT NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    versao_revisao VARCHAR(40) NOT NULL,
    motivo_revisao TEXT NULL,
    alteracoes_realizadas TEXT NULL,
    pendencias TEXT NULL,
    data_revisao DATE NULL,
    proxima_revisao DATE NULL,
    aprovado_por VARCHAR(180) NULL,
    status_revisao ENUM('RASCUNHO', 'EM_ANALISE', 'APROVADA', 'REPROVADA') NOT NULL DEFAULT 'RASCUNHO',
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_plancon_revisoes_plancon FOREIGN KEY (plancon_id) REFERENCES plancons(id),
    CONSTRAINT fk_plancon_revisoes_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_plancon_revisoes_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_plancon_revisoes_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_plancon_revisoes_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    UNIQUE KEY uk_plancon_revisoes_versao (plancon_id, versao_revisao),
    KEY idx_plancon_revisoes_escopo_status (conta_id, orgao_id, status_revisao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS incidentes_estrategias_pai (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    incidente_id BIGINT UNSIGNED NOT NULL,
    periodo_operacional_id BIGINT UNSIGNED NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    versao_pai VARCHAR(40) NOT NULL,
    estrategia_geral TEXT NOT NULL,
    taticas_prioritarias TEXT NULL,
    atividades_planejadas TEXT NULL,
    responsavel_execucao VARCHAR(180) NULL,
    recursos_necessarios TEXT NULL,
    areas_prioritarias TEXT NULL,
    status_pai ENUM('PROPOSTO', 'APROVADO', 'EM_EXECUCAO', 'ENCERRADO') NOT NULL DEFAULT 'PROPOSTO',
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_incidentes_pai_incidente FOREIGN KEY (incidente_id) REFERENCES incidentes(id),
    CONSTRAINT fk_incidentes_pai_periodo FOREIGN KEY (periodo_operacional_id) REFERENCES incidentes_periodos_operacionais(id),
    CONSTRAINT fk_incidentes_pai_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_incidentes_pai_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_incidentes_pai_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_incidentes_pai_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    UNIQUE KEY uk_incidentes_pai_versao (incidente_id, versao_pai),
    KEY idx_incidentes_pai_escopo (conta_id, orgao_id, incidente_id),
    KEY idx_incidentes_pai_status (status_pai)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS incidentes_operacoes_campo (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    incidente_id BIGINT UNSIGNED NOT NULL,
    periodo_operacional_id BIGINT UNSIGNED NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    frente_operacional VARCHAR(180) NOT NULL,
    setor_operacional VARCHAR(120) NULL,
    supervisor_frente VARCHAR(180) NULL,
    missao_tatica TEXT NULL,
    recursos_designados TEXT NULL,
    situacao_atual TEXT NULL,
    resultados_parciais TEXT NULL,
    status_operacao ENUM('ATIVA', 'PAUSADA', 'ENCERRADA') NOT NULL DEFAULT 'ATIVA',
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_incidentes_operacoes_incidente FOREIGN KEY (incidente_id) REFERENCES incidentes(id),
    CONSTRAINT fk_incidentes_operacoes_periodo FOREIGN KEY (periodo_operacional_id) REFERENCES incidentes_periodos_operacionais(id),
    CONSTRAINT fk_incidentes_operacoes_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_incidentes_operacoes_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_incidentes_operacoes_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_incidentes_operacoes_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    KEY idx_incidentes_operacoes_escopo (conta_id, orgao_id, incidente_id),
    KEY idx_incidentes_operacoes_status (status_operacao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS incidentes_planejamento_situacao (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    incidente_id BIGINT UNSIGNED NOT NULL,
    periodo_operacional_id BIGINT UNSIGNED NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    situacao_consolidada TEXT NOT NULL,
    prognostico TEXT NULL,
    cenario_provavel TEXT NULL,
    pendencias_criticas TEXT NULL,
    escalonamento_recomendado TEXT NULL,
    status_planejamento ENUM('EM_ANALISE', 'VALIDADO', 'ARQUIVADO') NOT NULL DEFAULT 'EM_ANALISE',
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_incidentes_planejamento_incidente FOREIGN KEY (incidente_id) REFERENCES incidentes(id),
    CONSTRAINT fk_incidentes_planejamento_periodo FOREIGN KEY (periodo_operacional_id) REFERENCES incidentes_periodos_operacionais(id),
    CONSTRAINT fk_incidentes_planejamento_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_incidentes_planejamento_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_incidentes_planejamento_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_incidentes_planejamento_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    KEY idx_incidentes_planejamento_escopo (conta_id, orgao_id, incidente_id),
    KEY idx_incidentes_planejamento_status (status_planejamento)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS incidentes_seguranca (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    incidente_id BIGINT UNSIGNED NOT NULL,
    periodo_operacional_id BIGINT UNSIGNED NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    riscos_operacionais TEXT NOT NULL,
    equipes_expostas TEXT NULL,
    medidas_controle TEXT NULL,
    epis_recomendados TEXT NULL,
    restricoes_operacionais TEXT NULL,
    interdicoes TEXT NULL,
    status_seguranca ENUM('ATIVA', 'EM_ALERTA', 'ENCERRADA') NOT NULL DEFAULT 'ATIVA',
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_incidentes_seguranca_incidente FOREIGN KEY (incidente_id) REFERENCES incidentes(id),
    CONSTRAINT fk_incidentes_seguranca_periodo FOREIGN KEY (periodo_operacional_id) REFERENCES incidentes_periodos_operacionais(id),
    CONSTRAINT fk_incidentes_seguranca_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_incidentes_seguranca_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_incidentes_seguranca_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_incidentes_seguranca_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    KEY idx_incidentes_seguranca_escopo (conta_id, orgao_id, incidente_id),
    KEY idx_incidentes_seguranca_status (status_seguranca)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS incidentes_desmobilizacao (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    incidente_id BIGINT UNSIGNED NOT NULL,
    conta_id BIGINT UNSIGNED NOT NULL,
    orgao_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NULL,
    criterios_desmobilizacao TEXT NOT NULL,
    recursos_liberados TEXT NULL,
    pendencias_finais TEXT NULL,
    licoes_iniciais TEXT NULL,
    situacao_final TEXT NULL,
    data_hora_inicio DATETIME NULL,
    data_hora_encerramento DATETIME NULL,
    status_desmobilizacao ENUM('PLANEJADA', 'EM_ANDAMENTO', 'CONCLUIDA') NOT NULL DEFAULT 'PLANEJADA',
    registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_incidentes_desmobilizacao_incidente FOREIGN KEY (incidente_id) REFERENCES incidentes(id),
    CONSTRAINT fk_incidentes_desmobilizacao_conta FOREIGN KEY (conta_id) REFERENCES contas(id),
    CONSTRAINT fk_incidentes_desmobilizacao_orgao FOREIGN KEY (orgao_id) REFERENCES orgaos(id),
    CONSTRAINT fk_incidentes_desmobilizacao_unidade FOREIGN KEY (unidade_id) REFERENCES unidades(id),
    CONSTRAINT fk_incidentes_desmobilizacao_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id),
    KEY idx_incidentes_desmobilizacao_escopo (conta_id, orgao_id, incidente_id),
    KEY idx_incidentes_desmobilizacao_status (status_desmobilizacao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
